#!/bin/bash
# deploy-to-pi4.sh — Deploy MaryJaneCoin to Pi4 (BridgePi)
#
# PREREQUISITES:
#   Run these ONE AT A TIME before executing this script:
#     eval $(ssh-agent)
#     ssh-add ~/.ssh/pi_key
#     export SSH_AUTH_SOCK=<value from above>
#
# IMPORTANT: Pi4 is ARM64. The binary in core/src/MaryJaneCoind was
# compiled for x86_64 and will NOT run on the Pi4.
#
# ARM64 Build Options:
#   Option A (RECOMMENDED): Build natively on Pi4 using build-on-pi4.sh
#   Option B: Cross-compile on WSL:
#     cd core && make HOST=aarch64-linux-gnu -C depends
#     ./configure --prefix=$(pwd)/depends/aarch64-linux-gnu
#     make -j$(nproc)
#
# This script sets up the directory structure, config, and bridge files.
# Run build-on-pi4.sh separately to compile the daemon.

set -e

PI4="jahvinci@10.0.0.80"
BRIDGE_DIR="/mnt/c/Users/balle/Desktop/MagnusOpus/Projects/MaryJaneCoin/bridge"
REMOTE_BRIDGE_DIR="~/maryjanecoin-bridge"
REMOTE_DATA_DIR="~/.MaryJaneCoin"
REMOTE_BUILD_DIR="~/MaryJaneCoin-Build"

RPC_USER="maryjrpc"
RPC_PASS="maryjpass420pi4"
RPC_PORT="14201"
P2P_PORT="14200"
AWS_SEED="35.155.206.7"

echo "============================================================"
echo "  MaryJaneCoin Pi4 Deployment Script"
echo "  Target: ${PI4}"
echo "============================================================"
echo ""

# --- Step 1: Check SSH connectivity ---
echo "[1/6] Checking SSH connectivity to Pi4..."
if ! ssh -o ConnectTimeout=10 -o BatchMode=yes "${PI4}" "echo 'SSH OK'" 2>/dev/null; then
    echo ""
    echo "ERROR: Cannot connect to Pi4 (${PI4})"
    echo ""
    echo "Load SSH keys first (run these ONE AT A TIME in your terminal):"
    echo "  eval \$(ssh-agent)"
    echo "  ssh-add ~/.ssh/pi_key"
    echo "  export SSH_AUTH_SOCK=\$SSH_AUTH_SOCK"
    echo ""
    echo "Then re-run this script with:"
    echo "  SSH_AUTH_SOCK=\$SSH_AUTH_SOCK bash deploy-to-pi4.sh"
    exit 1
fi
echo "  SSH connection OK."
echo ""

# --- Step 2: Create directory structure on Pi4 ---
echo "[2/6] Creating directory structure on Pi4..."
ssh "${PI4}" bash <<'REMOTE_EOF'
set -e
mkdir -p ~/MaryJaneCoin-Build/src
mkdir -p ~/.MaryJaneCoin
mkdir -p ~/maryjanecoin-bridge
echo "  Created: ~/MaryJaneCoin-Build/src"
echo "  Created: ~/.MaryJaneCoin"
echo "  Created: ~/maryjanecoin-bridge"
REMOTE_EOF
echo ""

# --- Step 3: Write MaryJaneCoin.conf ---
echo "[3/6] Writing ~/.MaryJaneCoin/MaryJaneCoin.conf on Pi4..."
ssh "${PI4}" bash -c "cat > ~/.MaryJaneCoin/MaryJaneCoin.conf" <<CONF_EOF
# MaryJaneCoin daemon configuration — Pi4 (BridgePi escrow node)
# Generated by deploy-to-pi4.sh

listen=1
daemon=1
server=1

# RPC credentials
rpcuser=${RPC_USER}
rpcpassword=${RPC_PASS}
rpcport=${RPC_PORT}
rpcallowip=127.0.0.1

# Network
port=${P2P_PORT}
maxconnections=16

# Seed nodes
addnode=${AWS_SEED}

# Logging
debug=0
printtoconsole=0

# Data directory (explicit — never use /tmp)
# datadir=/home/jahvinci/.MaryJaneCoin
CONF_EOF
echo "  Config written to ~/.MaryJaneCoin/MaryJaneCoin.conf"
echo ""

# --- Step 4: Copy bridge source to Pi4 ---
echo "[4/6] Copying bridge directory to Pi4..."
if [ ! -d "${BRIDGE_DIR}" ]; then
    echo "  WARNING: Bridge directory not found at ${BRIDGE_DIR}"
    echo "  Skipping bridge copy. Run again after bridge is available."
else
    # Sync bridge files, exclude node_modules
    rsync -avz --exclude='node_modules' --exclude='.env' \
        "${BRIDGE_DIR}/" "${PI4}:${REMOTE_BRIDGE_DIR}/"
    echo "  Bridge files synced to Pi4:${REMOTE_BRIDGE_DIR}/"

    # Install npm deps on Pi4
    echo "  Installing npm dependencies on Pi4..."
    ssh "${PI4}" bash -c "cd ${REMOTE_BRIDGE_DIR} && npm install --production 2>&1 | tail -5"
fi
echo ""

# --- Step 5: Set up systemd service file for MaryJaneCoind ---
echo "[5/6] Creating systemd service for MaryJaneCoind on Pi4..."
ssh "${PI4}" bash <<'REMOTE_EOF'
cat > /tmp/maryjanecoind.service <<'UNIT'
[Unit]
Description=MaryJaneCoin Daemon
After=network.target

[Service]
Type=forking
User=jahvinci
ExecStart=/home/jahvinci/MaryJaneCoin-Build/src/MaryJaneCoind
ExecStop=/home/jahvinci/MaryJaneCoin-Build/src/MaryJaneCoind stop
Restart=on-failure
RestartSec=30
TimeoutStartSec=120
TimeoutStopSec=60
PIDFile=/home/jahvinci/.MaryJaneCoin/MaryJaneCoind.pid

[Install]
WantedBy=multi-user.target
UNIT
echo "  Service file created at /tmp/maryjanecoind.service"
echo "  To install (run as root on Pi4):"
echo "    sudo cp /tmp/maryjanecoind.service /etc/systemd/system/"
echo "    sudo systemctl daemon-reload"
echo "    sudo systemctl enable maryjanecoind"
echo "    sudo systemctl start maryjanecoind"
REMOTE_EOF
echo ""

# --- Step 6: Summary ---
echo "[6/6] Deployment summary"
echo ""
echo "============================================================"
echo "  DONE — Files deployed to Pi4"
echo "============================================================"
echo ""
echo "  Config:  Pi4:~/.MaryJaneCoin/MaryJaneCoin.conf"
echo "  Build:   Pi4:~/MaryJaneCoin-Build/  (source goes here)"
echo "  Bridge:  Pi4:~/maryjanecoin-bridge/"
echo ""
echo "  NEXT STEPS:"
echo ""
echo "  1. Build MaryJaneCoind on Pi4 (ARM64):"
echo "     bash scripts/build-on-pi4.sh"
echo ""
echo "  2. Start the daemon:"
echo "     ssh ${PI4} '~/MaryJaneCoin-Build/src/MaryJaneCoind'"
echo ""
echo "  3. Check it's running:"
echo "     ssh ${PI4} '~/MaryJaneCoin-Build/src/MaryJaneCoind getinfo'"
echo ""
echo "  4. Generate escrow wallets:"
echo "     ssh ${PI4} 'python3 ~/maryjanecoin-bridge/scripts/generate-escrow-wallets.py --password YOUR_PASSWORD'"
echo ""
echo "  5. Distribute premine to Pi4:"
echo "     python3 scripts/distribute-to-pi4.sh"
echo ""
echo "  RPC: http://127.0.0.1:${RPC_PORT}  user=${RPC_USER}"
echo ""
